### ISSUE TITLE
Fix managment command help

### ISSUE THREAD

**Issue by piraz** [candango/firenado#13]
The management command help is broken. It should be fixed in order to be displayed according the command context.

It looks like the usage parameter it is not working as well.

**Comment by piraz** [comment]
Let's use click here.

http://click.pocoo.org/5/

**Comment by michael-lins** [comment]
*Flávio,*

Ok, I've got some info and although it is based on *optparse* I understood
their Philosophy.

​I'll use it.​

*Michael Alves Lins*
+55 61 9981-9555 (vivo/whatsapp)
michael@longanime.com.br (hangout/skype)
*"​Jesus​ está mudando minha vida. dia. após. dia"*

2016-01-27 18:28 GMT-02:00 Flavio Garcia <notifications@github.com>:
