### ISSUE TITLE
Start server listening on a unix socket

### ISSUE THREAD

**Issue by piraz** [candango/firenado#38]
As a user I want to have an option to start a server listening on unix socket.

User this gist as a guide: https://gist.github.com/superduper/5579037

**Comment by piraz** [comment]
HOW to test the socket:
http://stackoverflow.com/questions/19746230/how-to-do-tornado-httpserver-with-bind-unix-sock

**Comment by michael-lins** [comment]
advanced

*Michael Alves Lins*
+55 61 9981-9555 (vivo/whatsapp)
michael@longanime.com.br (hangout/skype)
*"​Jesus​ está mudando minha vida. dia. após. dia"*

2016-01-25 19:38 GMT-02:00 Flavio Garcia <notifications@github.com>:

**Comment by michael-lins** [comment]
Flávio,

Você vai usar unix sockets para comunicar com app de gerenciamento do
firenado? Seria para comunicar com que aplicação na mesma máquina? Ou
implementou para controle de acesso ao socket?

*Michael Alves Lins*
+55 61 9981-9555 (vivo/whatsapp)
michael@longanime.com.br (hangout/skype)
*"​Jesus​ está mudando minha vida. dia. após. dia"*

2016-01-28 2:58 GMT-02:00 Flavio Garcia <notifications@github.com>:

**Comment by piraz** [comment]
Quando a aplicação é inicializada ouvindo uma porta, toada a comunicação entre o seu webserver ou reverse proxy é via tcp, e vários handshakes são executados internamente. Em um site bastante congestionado isto pode impactar na carga e performance.

Utilizando um unix socket estes handshakes de tcp não existem, e teoricamente, há uma melhora na performance da sua aplicação.

Isto é uma escolha técnica do administrador da aplicação.

Com esta funcionalidade é possível mudar o comportamento via arquivo de configuração.

Se o socket for definido na sessão app, a porta é ignorada e a aplicação é inicializada com um unix socket.
