### ISSUE TITLE
Create watch command to provide (auto reload)

### ISSUE THREAD

**Issue by olavostauros** [candango/firenado#443]
you have to reload the server whenever you update files in the server

**Comment by piraz** [comment]
This should be done by adding either  `autoreload` or `debug` to the the app settings configuration.

If `autoreload` is set to true, the application will restart after a file is changed in the application directory.

```yaml
app:
  id: firenado-test-app
  component: testapp
  settings:
    autoreload: true
```

When `debug` is set to true, `autoreload` will be set to true but many other application configuration will be set to the debug mode also.

```yaml
app:
  id: firenado-test-app
  component: testapp
  settings:
    debug: true
```

To see the difference between `autoreload` and `debug` see the tornado documentation at: [tornado.web.Application.settings](https://www.tornadoweb.org/en/stable/web.html#tornado.web.Application.settings).

The app settings configuration was added by #163.

**Comment by piraz** [comment]
Nothing was implemented here, the solution is just pass either `autoreload` or `debug`  as true to the app settings.
