### ISSUE TITLE
Generate bower.json file from based on the assets component config file

### ISSUE THREAD

**Issue by michael-lins** [candango/firenado#86]
The assets component has the hability to store bower dependencies and map them to a proper static handler so it can be accessed on the web.

It would be good to have the hability of generate a bower.json file from those dependencies mapped on the assets component config file istead of managing dependencies in 2 files.

**Comment by piraz** [comment]
This is way out of the scope of this project.

We don't control and don't plan to control any javascript framework. Bower is obsolete and we're moving everything to yarn but this must be handled by other projects and by firenado.
